//
// Created by Hans Johnson on 2026-02-14.
//
#include <iostream>
#include "itkBinaryThresholdImageFilter.h"
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

int main(int argc, char * argv[])
{
  PARSE_ARGS; // <--- This is always the first line and is defined in SimpleThresholdCLP.h

  std::cout << "The number of iterations is: " << numberOfIterations << std::endl;
  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;

  using ImageType = itk::Image<short, 3>;
  using ReaderType = itk::ImageFileReader<ImageType>;
  using FilterType = itk::BinaryThresholdImageFilter<ImageType, ImageType>;
  using WriterType = itk::ImageFileWriter<ImageType>;

  try
  {
    auto reader = ReaderType::New();
    reader->SetFileName(input);

    auto filter = FilterType::New();
    filter->SetInput(reader->GetOutput());
    filter->SetLowerThreshold(static_cast<short>(lowThreshold));
    filter->SetUpperThreshold(static_cast<short>(highThreshold));
    filter->SetInsideValue(static_cast<short>(insideValue));
    filter->SetOutsideValue(static_cast<short>(outsideValue));

    auto writer = WriterType::New();
    writer->SetFileName(output);
    writer->SetInput(filter->GetOutput());
    writer->Update();
  }
  catch (const itk::ExceptionObject & err)
  {
    std::cerr << "ITK Exception caught:" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  catch (const std::exception & err)
  {
    std::cerr << "Exception caught: " << err.what() << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
